name: nextodo
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  dio: ^5.7.0
  flutter:
    sdk: flutter

  go_router: ^14.6.2
  persistent_bottom_nav_bar: ^6.2.1
  provider: ^6.1.2
  uuid: ^4.5.1
  vibration: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.2

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/app-logo.png"
  min_sdk_android: 26
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/app-logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Geist
      fonts:
        - asset: assets/fonts/Geist-Regular.ttf
        - asset: assets/fonts/Geist-Medium.ttf
          weight: 600
        - asset: assets/fonts/Geist-SemiBold.ttf
          weight: 700
